name: teachopencadd-t021 

channels: 
  - conda-forge 
  - defaults 

dependencies: 

  - python=3.11
  - jupyterlab 
  - numpy
  - pandas=2.0
  - rdkit
  - pyarrow
  - ipywidgets
  - scikit-learn
  - tensorflow
