name: teachopencadd-t001

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - jupyterlab
  - notebook=7
  - pandas=2.
  - rdkit=2023.9
  - chembl_webresource_client=0.10
  - iprogress
  - ipywidgets=8