name: teachopencadd-t022 

channels: 
  - conda-forge 
  - defaults 

dependencies: 

  - python=3.11
  - jupyterlab 
  - numpy
  - pandas
  - rdkit
  - pyarrow
  - scikit-learn
  - tensorflow
  - seaborn
