name: teachopencadd-t036
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - pytorch
  - tqdm
  - pytorch_geometric
  - torch-scatter
  - scipy
  - seaborn
  - rdkit
  - jupyterlab
  - pyarrow
