name: teachopencadd-h

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - jupyterlab
  - notebook=7
  - pandas=2.1
  - pyarrow
  - nglview=3
  - scikit-learn=1.4
  - biopython
  - bravado
