name: teachopencadd-d

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - jupyterlab
  - notebook>=7
  - rdkit=2023.9
  - pandas>=2.1
  - pyarrow
  - nglview=3
  - scikit-learn=1.4
