name: teachopencadd-e

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - jupyterlab
  - pandas=2.0
  - notebook=7
  - pyarrow
  - rdkit=2022.9
  - opencadd
  - pypdb=2
  - redo=2
  - nglview=3
  - numpy=1.21
  - mdanalysis=2
