name: teachopencadd-t012

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - jupyterlab
  - notebook=7
  - rdkit=2023.9
  - pandas=2.1
  - pyarrow
  - bravado=11
  - opencadd
  - nglview=3
