name: teachopencadd-t025 
channels: 
  - conda-forge 
  - defaults 
dependencies: 
  - python=3.9 
  - jupyterlab
  - numpy
  - pandas<=2.1
  - pyarrow
  - scikit-learn
  - seaborn
  - opencadd
  - kissim
